### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer-api#28]
**Assessment criteria**
- [ ] User can create a profile with a display name and picture

**Tasks**
- [ ] Create Model
- [ ] View for creating a profile ( no URL)
- [ ] View and URL for editing a profile
- [ ] Model deletes when user is deleted (on delete = cascade)
- [ ] View and URL for 
- [ ] Permission class (Team owner or Team member)
